name: Executar Bot da Copa do Mundo

on:
  schedule:
    # O GitHub usa o fuso horário UTC (3 horas à frente de Brasília)
    # Rodar às 03:05 UTC = 00:05 do Horário de Brasília (Madrugada)
    - cron: '5 3 * * *'
    
    # Rodar às 15:00 UTC = 12:00 do Horário de Brasília (Meio-dia)
    - cron: '0 15 * * *'
  workflow_dispatch: # Permite que você clique num botão para rodar manualmente se quiser testar

jobs:
  rodar-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v3

    - name: Configurar o Python na máquina virtual
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar as dependências do projeto
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Rodar o Script do Bot
      env:
        # Aqui nós injetamos os Secrets que guardamos no GitHub para o Python conseguir ler
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        APISPORTS_KEY: ${{ secrets.APISPORTS_KEY }}
      run: python notificador_copa.py
